### ISSUE TITLE
[企业实名认证]行业选择，省市区选择的底部弹出选择器需要优化

### ISSUE THREAD

**Issue by irideas** [jiliminbilly/lanxin-sign-issues#12]
- 增加省市区选择器的内容字体大小
- 增大选择器的展示面积
- 省市区选择器滚动选省时，会导致页面滚动。
- 省市区选择器滚动时会触发左右位置偏移。
- 下拉选择器增加[确认] 与 [取消] (视情况而定) 参考https://youzan.github.io/vant/#/zh-CN/area

 测试环境 iOS13 , iphone XS Max 真机

**Comment by jzz4012650** [comment]
已优化。
