### ISSUE TITLE
［发起签约］签署方列表的顺序应该按添加顺序1、2、3...排列，不是倒序

### ISSUE THREAD

**Issue by wujunyang0911** [jiliminbilly/lanxin-sign-issues#16]

**Comment by jiliminbilly** [comment]
问题出现在从联系人里选择， 从组织选择正常

**Comment by jiliminbilly** [comment]
应该按添加顺序1、2、3...排列，不是倒序

**Comment by jiliminbilly** [comment]
https://octodex.github.com/images/yaktocat.png

**Comment by cometruer** [comment]
lx客户端bug，从联系人选人返回的顺序是倒叙，从组织力选人返回的顺序是正序，
同时选联系人和组织，联系人的优先级高于组织的优先级，会排在组织的人前面

选联系人里的  abcd，出来是dcba
选组织里人 efgh，出来时efgh
如果选 ghab, 出来就是 bagh

**Comment by jiliminbilly** [comment]
如果短时间解决不了，就加个上下调整顺序的选择器，绕过这个问题吧。

**Comment by cometruer** [comment]
对lx选人界面来说，一直是没有顺序的，是一个staff集合。但是在签约的这个场景下，是需要排序并且排序需要准确的。因此建议在选人后可以进行手动排序。前端这边先调研一个适合移动端用户排序的体验加以实施。

**Comment by wujunyang0911** [comment]
已验证解决了。

**Comment by wujunyang0911** [comment]
问题依然存在。安卓手机测试的。

**Comment by cometruer** [comment]
因客户端返回无序联系人，目前解决方案为 前端页面加入拖动按钮，可以手动拖动修改签约顺序。大约11点20更新前端代码

**Comment by wujunyang0911** [comment]
已验证，拖动排序可以解决问题。
