### ISSUE TITLE
［合同签署］合同签署页面查看合同文件时，无法双指放大文件，合同细节查看不清楚

### ISSUE THREAD

**Issue by wujunyang0911** [jiliminbilly/lanxin-sign-issues#19]

**Comment by jiliminbilly** [comment]
https://octodex.github.com/images/yaktocat.png

**Comment by wujunyang0911** [comment]
刚发现，先单击一下屏幕后，就可以放大了。应该在未单击屏幕时，也可以放大。

**Comment by dreamllq** [comment]
该功能暂时修改成使用蓝信的能力来预览原pdf文件内容，这样能够直接查看原文件，若还不清楚则需要更换原文件

**Comment by dreamllq** [comment]
该功能若需要优化，需要给出产品的设计，这块功能基于现有的代码和文档无法开发
