### ISSUE TITLE
［发起签约］选择人员后，外部已选的人员没有进入签署方列表

### ISSUE THREAD

**Issue by wujunyang0911** [jiliminbilly/lanxin-sign-issues#24]

**Comment by cometruer** [comment]
初步判断是ios选人组件bug，当选外部人员时，staffId不返回。

**Comment by irideas** [comment]
这与iOS 安卓无关，BUG是选择外部联系人时无法获得Staffid。
下一步该应用会变成ISV应用并在全组织开通，就可以解决。

**Comment by wujunyang0911** [comment]
> 这与iOS 安卓无关，BUG是选择外部联系人时无法获得Staffid。
> 下一步该应用会变成ISV应用并在全组织开通，就可以解决。

说的是另一个问题，是选本组织内部人员也无法进入列表。

**Comment by wujunyang0911** [comment]
这个问题已验证解决了。

**Comment by cometruer** [comment]
每个组织下都默认按照应用，就可以选外部的人了
