### ISSUE TITLE
［用户登录］蓝信用户和电子签约用户不同步，切换蓝信用户时，电子签约用户未同步

### ISSUE THREAD

**Issue by wujunyang0911** [jiliminbilly/lanxin-sign-issues#30]
操作流程：先登录蓝信刘伟，电子签约刘伟，退出蓝信用户，重新登录廖暖香，蓝信为廖暖香，电子签约仍然是刘伟，电子签约应该为廖暖香，前端问题。

**Comment by jiliminbilly** [comment]
前端清缓存问题

**Comment by lnend1992** [comment]
增加登录态cookie保存，解决客户端没有清空localStorage导致账号混乱的问题
