### ISSUE TITLE
［合同签署］交互问题

### ISSUE THREAD

**Issue by wujunyang0911** [jiliminbilly/lanxin-sign-issues#34]
合同签署页面，当用户向下滑动屏幕后，点击“签署”，看不到印章。
原因：当前无论用户停留在页面什么位置，点击“签署”，印章始终在第一页上。
期望：无论当前无论用户停留在页面什么位置，点击“签署”，能在当前屏幕的页面内显示印章。

**Comment by jiliminbilly** [comment]
是需求，不是bug

**Comment by wujunyang0911** [comment]
已转需求。
