### ISSUE TITLE
[签约成功]签约成功页面的合同有效期限显示不对

### ISSUE THREAD

**Issue by wujunyang0911** [jiliminbilly/lanxin-sign-issues#35]
前后时间肯定不是一样的。

**Comment by jiliminbilly** [comment]
![651581261827_ pic](https://user-images.githubusercontent.com/6356583/74104832-ac3a5080-4b93-11ea-817c-5980f385b327.jpg)

**Comment by jiliminbilly** [comment]
前端发起时间 参数不对

**Comment by cometruer** [comment]
前端开始时间结束时间写成一个值，待上线后验证。

**Comment by jiliminbilly** [comment]
已修复
