### ISSUE TITLE
[合同发起] 发起接口提示”您尚有5个未支付的合同，不能再新建合同“

### ISSUE THREAD

**Issue by dreamllq** [jiliminbilly/lanxin-sign-issues#39]
<img width="404" alt="WechatIMG400" src="https://user-images.githubusercontent.com/6227563/74104580-0a196900-4b91-11ea-97ea-9d7b930554b9.png">

**Comment by cometruer** [comment]
后端问题，之前逻辑有5个合同的限制，需要真相科技后端处理

**Comment by wujunyang0911** [comment]
研发反馈已改完，待验证

**Comment by wujunyang0911** [comment]
验收OK
