### ISSUE TITLE
［发起签约］发起无序签约，签署方为4人，提交之后，变成了3人，随机漏掉一个人

### ISSUE THREAD

**Issue by wujunyang0911** [jiliminbilly/lanxin-sign-issues#42]

**Comment by wujunyang0911** [comment]
无论是否选择了顺序签，签约完成后的页面中，签署方都会少一个

**Comment by cometruer** [comment]
通过前端排查，假设用手机5个用户staffId去真相后端换取5个真相用户，用户信息虽然返回了5个用户信息，但是这5个真相用户中有的对象里没有id字段，致使发起签约时漏用户的情况。请真相服务端排查下这种取失败的情况。

**Comment by irideas** [comment]
![image](https://user-images.githubusercontent.com/192851/74105610-5ddc8000-4b9a-11ea-9b97-f298d634e92a.png)
![image](https://user-images.githubusercontent.com/192851/74105611-62089d80-4b9a-11ea-8adb-fd4e2810c4b4.png)

**Comment by irideas** [comment]
![image](https://user-images.githubusercontent.com/192851/74105619-6f258c80-4b9a-11ea-94e5-f82baa01d17c.png)

**Comment by wujunyang0911** [comment]
已验证OK
