### ISSUE TITLE
 蓝信云盘选择pdf失效

### ISSUE THREAD

**Issue by jiliminbilly** [jiliminbilly/lanxin-sign-issues#5]
选合同文件时，在云盘选了pdf文件了，还提示只能选pdf文件，iOS模拟器没问题，ios真机部分也有该问题，安卓有该问题，可能部分机型适配问题 @前端 赵路

**Comment by wujunyang0911** [comment]
因涉及客户端排查问题，时间紧急，临时方案：云盘不过滤文件类型（含上传合同pdf和上传签章png两个场景），当用户选择文件后，再判断格式。

**Comment by wujunyang0911** [comment]
已用临时方案解决。
